export const dom = {
  appShell: document.getElementById('app-shell'),
  loader: document.getElementById('startup-loader'),
  composer: document.getElementById('composer'),
  noteForm: document.getElementById('note-form'),
  noteIdInput: document.getElementById('note-id'),
  titleInput: document.getElementById('note-title'),
  categoryInput: document.getElementById('note-category'),
  bodyInput: document.getElementById('note-body'),
  saveButton: document.getElementById('save-note'),
  cancelEditButton: document.getElementById('cancel-edit'),
  composerTitle: document.getElementById('composer-title'),
  formMode: document.getElementById('form-mode'),
  previewPanel: document.getElementById('markdown-preview'),
  previewToggle: document.getElementById('preview-toggle'),
  controlsSection: document.querySelector('.controls'),
  controlsToggle: document.getElementById('controls-toggle'),
  searchInput: document.getElementById('search-notes'),
  sortSelect: document.getElementById('sort-notes'),
  filterGroup: document.getElementById('filter-group'),
  pinnedSection: document.getElementById('pinned-section'),
  pinnedNotesContainer: document.getElementById('pinned-notes'),
  notesContainer: document.getElementById('notes-container'),
  emptyState: document.getElementById('empty-state'),
  notesCount: document.getElementById('notes-count'),
  themeToggle: document.getElementById('theme-toggle'),
  themeIcon: document.querySelector('#theme-toggle .theme-icon'),
  toastStack: document.getElementById('toast-stack'),
  deleteModal: document.getElementById('delete-modal'),
  deleteTitle: document.getElementById('delete-title'),
  deleteText: document.getElementById('delete-text'),
  importFile: document.getElementById('import-file'),
  bulkToolbar: document.getElementById('bulk-toolbar'),
  selectedCount: document.getElementById('selected-count'),
  cursorGlow: document.getElementById('cursor-glow'),
  statEls: {
    total: document.getElementById('total-stat'),
    pinned: document.getElementById('pinned-stat'),
    favorites: document.getElementById('favorite-stat'),
    archived: document.getElementById('archived-stat')
  }
};
